name: aqualime
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.0
  intl: ^0.18.1
  grouped_action_buttons: ^0.0.4
  logger: ^2.4.0
  device_info_plus: ^11.5.0
  lottie: ^3.3.1

  flutter_udid: ^4.0.0

  # NoSQL
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  shared_preferences: ^2.1.1

  # GetX
  get: ^4.6.6
  get_storage: ^2.1.1
  path_provider: ^2.1.4

  # Google Map
  location: ^5.0.0
  google_maps_flutter: ^2.12.1
  point_in_polygon: ^1.0.0
  url_launcher: ^6.2.4
  geolocator: ^10.1.0

  # firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.3.7
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf